routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('projects', 'ProjectController');
Route::get('/', 'ProjectController@index');

Route::resource('entries', 'EntryController');
Route::delete('entries/destroy/{id}', 'EntryController@destroy');
Route::get('entries/create/{id}', 'EntryController@create');

Route::resource('templates', 'TemplateController');

Route::get('templates/{id}', 'TemplateController@edit');

Auth::routes();

app/Models/Project.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Project extends Model
{
    use HasFactory;

    protected $table = 'projects';
    
    protected $primaryKey = 'id';
    
    protected $guarded = ['id'];

    /**
     * The "booted" method of the model.
     *
     * @return void
     */
    protected static function booted()
    {
        static::creating(function ($project) {
            $project->user = auth()->user()->id;
        });
    }

    public function setTagsAttribute($value){
        $this->attributes['tags'] = json_encode($value);
    }

    public function getTagsAttribute(){
        return json_decode($this->attributes['tags']);
    }

    public $timestamps = true;
}

app/Http/Controllers/API/ProjectController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use App\Models\Project;
use App\Models\Entry;

use App\Http\Requests\ProjectRequest;

class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function getAllProjects()
    {
        $projects = Project::all();

        foreach($projects as $project){
            $project->numberOfProjects = Entry::where('project_id', $project->id)->count();
        }

        return response()->json($projects);
    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use App\Models\Project;
use App\Models\Entry;

use App\Http\Requests\ProjectRequest;

class ProjectController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $projects = Project::where('user', auth()->user()->id)->get();

        foreach($projects as $project){
            $project->numberOfProjects = Entry::where('project_id', $project->id)->count();
        }
        
        return view('projects.index', compact('projects'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('projects.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProjectRequest $request)
    {
        $newProject = Project::create($request->all());
        return redirect()->route('projects.show', $newProject->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $project = Project::findOrFail($id);
        $entries = Entry::where('project_id', $project->id)->get();
        return view('projects.view', compact('project', 'entries'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }


    public function getAllProjects(Request $request){
        if ($request->ajax()){
            $projects = Project::where('user', auth()->user()->id)->get();

            //Get number of entries per project for the badge count.
            $numberOfEntries = [];

            foreach($projects as $project){
                $numberOfEntries[] = Entry::where('project_id', $project->id)->count();
            }
        }
    }
}

resources/views/projects/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Create a New Project</div>
                <div class="card-body">
                    <form method="POST" action="{{ route('projects.store') }}">
                        @csrf
                        <div class="form-group">
                            <label for="name">Project Name</label>
                            <input type="text" name="name" class="form-control" required>
                        </div>

                        <div class="form-group">
                            <label for="tags">Tags</label>
                            <input type="text" data-plugin="tokenfield" name="tags" class="form-control tokenfield">
                        </div>

                        <button type="submit" class="btn btn-primary float-right">Create Project</button>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
<script>
    $('.tokenfield').tokenfield()
</script>
@endsection

resources/views/projects/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <span> My Projects </span>
                    <a href="{{ route('projects.create') }}" class="btn btn-primary btn-sm float-right">Create a new Project</a>
                </div>
                <div id="projects"/>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')

<script type="text/javascript">
    var data = @json($projects, JSON_PRETTY_PRINT);
    console.log(data);
</script>

@endsection

resources/views/projects/view.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <span> {{ $project->name }} entries </span>
                    <a href="{{ url()->to('/') . '/entries/create/' . $project->id }}" class="btn btn-primary btn-sm float-right">Create a new entry</a>
                </div>

                <div id="entries"/>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')

<script type="text/javascript">
var data = @json($entries, JSON_PRETTY_PRINT);
</script>

@endsection