routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('projects', 'ProjectController');
Route::get('/', 'ProjectController@index');

Route::resource('entries', 'EntryController');
Route::delete('entries/destroy/{id}', 'EntryController@destroy');
Route::get('entries/create/{id}', 'EntryController@create');

Route::resource('templates', 'TemplateController');

Route::get('templates/{id}', 'TemplateController@edit');

Auth::routes();

app/Models/Entry.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Entry extends Model
{
    protected $table = 'entries';
    
    protected $primaryKey = 'id';
    
    protected $guarded = ['id'];

    public $timestamps = true;

    public function setContentAttribute($value){
        $this->attributes['content'] = $value;
    }

    public function setTagsAttribute($value){
        $this->attributes['tags'] = json_encode($value);
    }

    public function getTagsAttribute(){
        return json_decode($this->attributes['tags']);
    }
}

app/Http/Controllers/API/EntryController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use App\Models\Entry;
use App\Models\Project;
use App\Models\Template;
use App\Http\Requests\EntryRequest;

use Sinnbeck\Markdom\Facades\Markdom;

class EntryController extends Controller
{
    public function getEntries($projectId)
    {
        $project = Project::find($projectId);
        $entries = [];
        if (isset($project)){
            $entries = Entry::where('project_id', $project->id)->get();
        }

        return $entries;
    }

    public function store(EntryRequest $request)
    {
        $newEntry = Entry::create($request->all());
        return response()->json(['entry' => $newEntry], Response::HTTP_CREATED);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $selectedEntry = Entry::find($id);
        if (isset($selectedEntry)){
            $selectedEntry->content = Markdom::toHtml($selectedEntry->content);
            return response()->json(['entry' => $selectedEntry], Response::HTTP_OK);
        } else {
            return response()->json(['error' => "Entry not found."], Response::HTTP_NOT_FOUND);
        }
    }

    public function update(EntryRequest $request, $id)
    {
        $selectedEntry = Entry::find($id);
        if (isset($selectedEntry)){
            $selectedEntry->update($request->all());
            return response()->json(['entry' => $selectedEntry], Response::HTTP_OK);
        } else {
            return response()->json(['error' => "Entry not found."], Response::HTTP_NOT_FOUND);
        }
    }

    public function destroy($id)
    {
        $selectedEntry = Entry::find($id);

        if (isset($selectedEntry)){
            $selectedEntry->delete();
            return response()->json(['error' => "Entry successfully deleted."], Response::HTTP_NO_CONTENT);
        } else {
            return response()->json(['error' => "Entry not found."], Response::HTTP_NOT_FOUND);
        }
    }
}

app/Http/Controllers/EntryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use App\Models\Entry;
use App\Models\Project;
use App\Models\Template;
use App\Http\Requests\EntryRequest;

use Sinnbeck\Markdom\Facades\Markdom;

class EntryController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($projectId)
    {
        $project = Project::find($projectId);
        $templates = Template::where('project_id', $project->id)->orWhereNull('project_id')->get();
        if (isset($project)){
            return view('entries.create', compact('project', 'templates'));
        } else {
            return redirect()->back();
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(EntryRequest $request)
    {
        $newEntry = Entry::create($request->all());
        return redirect()->route('entries.show', $newEntry->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $selectedEntry = Entry::find($id);
        if (isset($selectedEntry)){
            $selectedEntry->content = Markdom::toHtml($selectedEntry->content);
            return view('entries.view', compact('selectedEntry'));
        } else {
            return redirect()->route('projects.index');
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $entry = Entry::find($id);
        $templates = Template::where('project_id', $entry->project_id)->orWhereNull('project_id')->get();
        if (isset($entry)){
            return view('entries.edit', compact('entry', 'templates'));
        } else {
            return redirect()->back();
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(EntryRequest $request, $id)
    {
        $selectedEntry = Entry::find($id);
        if (isset($selectedEntry)){
            $selectedEntry->update($request->all());
            return redirect()->route('entries.show', $selectedEntry->id);
        } else {
            return redirect()->back();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $selectedEntry = Entry::find($id);
        $entryProjectId = $selectedEntry->project_id;

        if (isset($selectedEntry)){
            $selectedEntry->delete();
        }

        return redirect()->route('projects.show', $entryProjectId);
    }
}

resources/views/entries/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Create New Entry</div>
                <div class="card-body">
                    <form method="POST" action="{{ route('entries.store') }}">
                        @csrf
                        <input type="hidden" name="project_id" value="{{$project->id}}">
                        <div class="form-group">
                            <label for="title">Title</label>
                            <input type="text" name="title" class="form-control" required>
                        </div>
                        
                        <div class="form-group template-entry">
                            <label for="template_id">Content Template</label>
                            <select class="form-control template_id">
                                <option value="">Select a Template</option>
                                @foreach ($templates as $template)
                                    <option value="{{ $template->content }}">{{ $template->title }}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="content">Content</label>
                            <textarea name="content" class="form-control entry-content"></textarea>
                        </div>

                        <div class="form-group">
                            <label for="tags">Tags</label>
                            <input type="text" data-plugin="tokenfield" name="tags" class="form-control tokenfield">
                        </div>

                        <button type="submit" class="btn btn-primary float-right">Create Entry</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
<script>
    $('.tokenfield').tokenfield();
    var simplemde = new EasyMDE();
    simplemde.value($('.template_id').val());

    $('.template_id').on('change', function(){
        simplemde.value(this.value);
    });
</script>
@endsection

resources/views/entries/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    Edit {{ $entry->title }}
                    <span class="float-right">
                        <form method="POST" action="{{ url('entries/destroy/' . $entry->id) }}">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                        </form>
                    </span>
                </div>
                <div class="card-body">
                    <form method="POST" action="{{ route('entries.update', $entry->id) }}">
                        @csrf
                        @method('PUT')
                        <input type="hidden" name="project_id" value="{{$entry->id}}">
                        <div class="form-group">
                            <label for="title">Title</label>
                            <input type="text" name="title" class="form-control" value="{{ $entry->title }}" required>
                        </div>

                        <div class="form-group template-entry">
                            <label>Content Template</label>
                            <select class="form-control template_id">
                                <option id="previousContentInput" value="">Select a Template</option>
                                @foreach ($templates as $template)
                                    <option value="{{ $template->content }}">{{ $template->title }}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="content">Content</label>
                            <textarea name="content" class="form-control entry-content">{!! $entry->content !!}</textarea>
                        </div>

                        <div class="form-group">
                            <label for="tags">Tags</label>
                            <input type="text" data-plugin="tokenfield" name="tags" value="{{ $entry->tags }}" class="form-control tokenfield">
                        </div>

                        <button type="submit" class="btn btn-primary float-right">Edit Entry</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
<script>
    $('.tokenfield').tokenfield()
    var simplemde = new EasyMDE({ element: $(".entry-content")[0] });

    $('.template_id').on('change', function(){
        simplemde.value(this.value);
    });
</script>
@endsection

resources/views/entries/view.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    {{ $selectedEntry->title }}
                    <span class="float-right">
                        <a href="{{ route('entries.edit', $selectedEntry->id) }}" class="btn btn-sm btn-primary">Edit</a>
                    </span>
                </div>

                <div class="card-body">
                    {!! $selectedEntry->content !!}
                    <br>
                    Tags: {{ $selectedEntry->tags }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection